# Generated by Django 2.2.3 on 2019-11-11 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('perfil', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('fecha_lanzamiento', models.DateField()),
                ('duracion', models.IntegerField(default=0)),
                ('descripcion', models.TextField()),
                ('portada', models.ImageField(upload_to='')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMovies.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Peli_Dir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMovies.Director')),
                ('peliculas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMovies.Pelicula')),
            ],
        ),
    ]
